### ISSUE TITLE
mkfs.xfs -dsu=65536 sw=1 core (version 5.4.0)

### ISSUE THREAD

**Issue by wangyugui** [oracle/oracle-linux#68]
Hi,

'/usr/sbin/mkfs.xfs -dsu=65536 sw=1 /mnt/test/260.410113' triggered a core

```
# gdb /usr/sbin/mkfs.xfs core.410299
Reading symbols from /usr/sbin/mkfs.xfs...Reading symbols from .gnu_debugdata for /usr/sbin/mkfs.xfs...(no debugging symbols found)...done.
(no debugging symbols found)...done.
[New LWP 410299]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/usr/sbin/mkfs.xfs -dsu=65536 sw=1 /mnt/test/260.410113'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f213b4eca4f in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: yum debuginfo-install xfsprogs-5.4.0-1.0.1.el8.x86_64
(gdb) where
#0  0x00007f213b4eca4f in raise () from /lib64/libc.so.6
#1  0x00007f213b4bfdb5 in abort () from /lib64/libc.so.6
#2  0x00007f213b4bfc89 in __assert_fail_base.cold.0 () from /lib64/libc.so.6
#3  0x00007f213b4e53a6 in __assert_fail () from /lib64/libc.so.6
#4  0x0000563c88c07da5 in main ()
# /usr/sbin/mkfs.xfs -V
mkfs.xfs version 5.4.0

```

**Comment by Halesharry** [comment]
HI i did not understand this please explain me. <a href="https://financeinvestation.comhttps://seeingthebrightside.com/study-strategy-to-study-smarter/">.</a>

**Comment by tvierling** [comment]
I'm sorry this report was overlooked. You didn't include the actual core file, or a diagnostic report of your system (sosreport, which should be included with all reports of crashes). If this reproduces on an up-to-date system, please file a new report, attaching the core file and a sosreport so we can see the context of the crash.
