### ISSUE TITLE
xfs_repair core (version 5.4.0)

### ISSUE THREAD

**Issue by wangyugui** [oracle/oracle-linux#69]
Hi,

'/usr/sbin/xfs_repair -n /dev/sdb2' triggered a core.

```
# gdb /usr/sbin/xfs_repair core.3466528
Reading symbols from /usr/sbin/xfs_repair...Reading symbols from .gnu_debugdata for /usr/sbin/xfs_repair...(no debugging symbols found)...done.
(no debugging symbols found)...done.
[New LWP 3466693]
[New LWP 3466696]
[New LWP 3466732]
[New LWP 3466694]
[New LWP 3466528]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/usr/sbin/xfs_repair -n /dev/sdb2'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f72718d8a4f in raise () from /lib64/libc.so.6
[Current thread is 1 (Thread 0x7f726cf94700 (LWP 3466693))]
Missing separate debuginfos, use: yum debuginfo-install xfsprogs-5.4.0-1.0.1.el8.x86_64
(gdb) where
#0  0x00007f72718d8a4f in raise () from /lib64/libc.so.6
#1  0x00007f72718abdb5 in abort () from /lib64/libc.so.6
#2  0x00007f72718abc89 in __assert_fail_base.cold.0 () from /lib64/libc.so.6
#3  0x00007f72718d13a6 in __assert_fail () from /lib64/libc.so.6
#4  0x000055627782b46e in mark_inode_rl ()
#5  0x000055627782c1ef in compute_refcounts ()
#6  0x000055627781c40d in compute_ag_refcounts ()
#7  0x0000556277885583 in workqueue_thread ()
#8  0x00007f7271eac1df in start_thread () from /lib64/libpthread.so.0
#9  0x00007f72718c3d83 in clone () from /lib64/libc.so.6
(gdb) quit
# /usr/sbin/xfs_repair -V
xfs_repair version 5.4.0
```

**Comment by tvierling** [comment]
I'm sorry this report was overlooked. You didn't include the actual core file, or a diagnostic report of your system (sosreport, which should be included with all reports of crashes). If this reproduces on an up-to-date system, please file a new report, attaching the core file and a sosreport so we can see the context of the crash.
